### PR TITLE
Fix StackOverflowError caused by recursive calls in fetchToken for files with huge amounts of commented lines

### LINKED ISSUE #1603: IDE functionality is broken by stack overflow in directives when a file is full of comments
**Version(s)**

0.1.17

**Describe the bug**

The BSP server logs are full of stack traces. This seems to affect IDE functionality by showing stale diagnostics:

image

which is fixed the moment you delete a problematic file:

image

**To Reproduce**

Open a project in Metals which contains a file with over 100 lines of comments. For example:

<details>
<summary>lotsa comments inside</summary>

```scala
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
// aaaaaaaaaaaaa
```

</details>

It may not sound realistic, but sometimes you comment out an entire file and that does surface the error.

Look at the output:

image

**Expected behaviour**
No stack overflows :)

### PR DESCRIPTION
**Pull request by KacperFKorban**
Since Java compiler can't rewrite tail recursion, tail recursive functions have to be manually rewritten to use iteration.

should fix virtuslab/scala-cli#1603

### CODE REVIEW

File: src/main/java/com/virtuslab/using_directives/custom/Scanner.java [hunk 1]
```diff
@@ -415,6 +415,13 @@ private boolean pastBlankLine() {
   }
 
   private void fetchToken() {
+    boolean cont = true;
+    while (cont) {
+      cont = doFetchToken();
+    }
```
Comment (szymon-rd) [inline src/main/java/com/virtuslab/using_directives/custom/Scanner.java]:
```suggestion
    while(doFetchToken()) { };
```

**Review by szymon-rd — APPROVED** [review]
